# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "russmckendrick/centos71"
  config.vm.network "private_network", ip: "192.168.33.11"
  HOSTNAME = 'zabbix'
  DOMAIN   = 'media-glass.es'
  Vagrant.require_version '>= 1.7.0'
  config.ssh.insert_key = false

  config.vm.host_name = HOSTNAME + '.' + DOMAIN
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/monitoring_docker"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "512"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.manifest_file  = "site.pp"
        puppet.module_path = "puppet/modules"
        puppet.options = "--verbose --debug"
  end

end 